name: linux-make

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: install
      run: cd tests && bash configure.sh

    - name: test
      id: "_1"
      run: cd tests && make all
