name: C++ CI with Make

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure #installs google test
      id: "_0"
      run: ./configure
    - name: execution #run tests
      id: "_1"
      run: make all
    - name: cleaning #clean unneded files
      id: "_2"
      run: make ckean
    #- name: make check
    #  run: make check
    #- name: make distcheck
    #  run: make distcheck
