name: C++ CI with Make

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure #installs google test
      id: "_0"
      run: ls -lrt && pwd && cd $(git rev-parse --git-dir)/../test && ./configure

    - name: execution #run tests
      id: "_1"
      run: cd $(git rev-parse --git-dir)/../test && make all

    #- name: cleaning #clean unneded files
      #id: "_2"
      #run: cd test && make all
    #- name: make check
    #  run: make check
    #- name: make distcheck
    #  run: make distcheck
